### PR TITLE
Run2 ultra legacy add el syst variables

### PR DESCRIPTION
**Pull request by jalmond**

### CODE REVIEW

**Review by jbhyun — APPROVED** [review]
Looks fine to me.

**Comment by jbhyun** [comment]
References for anybody interested in those variables: https://twiki.cern.ch/twiki/bin/view/CMS/EgammaMiniAODV2#Energy_Scale_and_Smearing

**Comment by sansan9401** [comment]
Sorry for the late review. Is it correct there is no `electron_Energy_SigmaPhi_Down`? @jalmond

**Comment by jalmond** [comment]
> Sorry for the late review. Is it correct there is no `electron_Energy_SigmaPhi_Down`? @jalmond

Yeah this is true, the twiki (https://twiki.cern.ch/twiki/bin/view/CMS/EgammaMiniAODV2#Applying_the_Energy_Scale_and_sm) states "For Smearing "PhiUp" and "PhiDown" are currently identical"

**Pull request merged**
